plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-packaging
  - rubocop-rake
  - rubocop-rails
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "test/dummy/**/*"
  NewCops: enable
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Minitest/MultipleAssertions:
  Max: 4

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
