plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-packaging
  - rubocop-rake
  - rubocop-rails
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "test/dummy/**/*"
  NewCops: enable
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Minitest/MultipleAssertions:
  Max: 4

Style/Documentation:
  Exclude:
    - "lib/generators/money_attribute/initializer_generator.rb"
    - "lib/money_attribute/configuration.rb"
    - "lib/money_attribute/parser.rb"
    - "lib/money_attribute/railtie.rb"
    - "test/**/*"

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
